version: v2beta1
name: teraflowsdn-dev

# --- Images ---
images:
  device:
    image: localhost:32000/tfs/device:dev
    dockerfile: ${CONTROLLER_FOLDER}/src/device/Dockerfile
    context: ${CONTROLLER_FOLDER}
  # context:
  #   image: labs.etsi.org:5050/tfs/controller/context:dev
  #   dockerfile: ./src/context/Dockerfile
  #   context: .
  # service:
  #   image: labs.etsi.org:5050/tfs/controller/service:dev
  #   dockerfile: ./src/service/Dockerfile
  #   context: .
  # nbi:
  #   image: labs.etsi.org:5050/tfs/controller/nbi:dev
  #   dockerfile: ./src/nbi/Dockerfile
  #   context: .
  # webui:
  #   image: labs.etsi.org:5050/tfs/controller/webui:dev
  #   dockerfile: ./src/webui/Dockerfile
  #   context: .

# --- Deployments ---
deployments:
  device:
    kubectl:
      manifests:
        - ${CONTROLLER_FOLDER}/manifests/deviceservice.yaml
  # context:
  #   kubectl:
  #     manifests:
  #       - ./manifests/contextservice.yaml
  # service:
  #   kubectl:
  #     manifests:
  #       - ./manifests/serviceservice.yaml
  # nbi:
  #   kubectl:
  #     manifests:
  #       - ./manifests/nbiservice.yaml
  # webui:
  #   kubectl:
  #     manifests:
  #       - ./manifests/webuiservice.yaml

# --- Development Settings: File Sync and Port Forwarding ---
dev:
  device:
    labelSelector:
      app: deviceservice
    sync:
      # This rule will first download (mirrorRemote) the container’s contents into your local folder.
      - path: "${CONTROLLER_FOLDER}/src/device:/var/teraflow/device"
        initialSync: mirrorRemote
      - path: "${CONTROLLER_FOLDER}/src/common:/var/teraflow/common"
        initialSync: mirrorRemote
      - path: "${CONTROLLER_FOLDER}/src/context/client:/var/teraflow/context/client"
        initialSync: mirrorRemote
    ports:
      - port: "2020"
      - port: "9192"

  # context:
  #   imageSelector: labs.etsi.org:5050/tfs/controller/context:dev
  #   sync:
  #     - path: ./src/context
  #       containerPath: /var/teraflow/context
  #     - path: ./src/common
  #       containerPath: /var/teraflow/common
  #   ports:
  #     - port: "1010"
  #     - port: "9192"

  # service:
  #   imageSelector: labs.etsi.org:5050/tfs/controller/service:dev
  #   sync:
  #     - path: ./src/service
  #       containerPath: /var/teraflow/service
  #   ports:
  #     - port: "3030"
  #     - port: "9192"

  # nbi:
  #   imageSelector: labs.etsi.org:5050/tfs/controller/nbi:dev
  #   sync:
  #     - path: ./src/nbi
  #       containerPath: /var/teraflow/nbi
  #   ports:
  #     - port: "8080"
  #     - port: "9090"
  #     - port: "9192"
  #     - port: "8762"

  # webui:
  #   imageSelector: labs.etsi.org:5050/tfs/controller/webui:dev
  #   sync:
  #     - path: ./src/webui
  #       containerPath: /var/teraflow/webui
  #   ports:
  #     - port: "8004"
  #     - port: "3000"

# --- Development Pipeline ---
pipelines:
  dev:
    run: |-
      echo "Deploying all components for DevSpace..."
      create_deployments --all
      echo "Starting dev mode for device, context, service, nbi, webui..."
      start_dev device
      echo "DevSpace deployment complete."