name: TFS LXD Bootstrap

on:
  workflow_dispatch:
    inputs:
      devspace_mode:
        description: "Enable DEVSPACE_MODE? (yes/no)"
        required: false
        default: "no"
  push:
    branches: [ main ]

jobs:
  bootstrap:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make KVM usable for LXD VM mode on hosted Linux runners
      - name: Enable /dev/kvm
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm || true
          ls -l /dev/kvm || (echo "ERROR: /dev/kvm not available"; exit 1)

      - name: Run TFS bootstrap script (does all installs & VM work)
        env:
          DEVSPACE_MODE: ${{ github.event.inputs.devspace_mode || 'no' }}
        run: |
          set -euxo pipefail
          chmod +x ./tfs-lxd.sh
          # Script installs snapd/LXD if needed, runs lxd init, launches Ubuntu 24.04 VM,
          # runs MicroK8s + addons, deploys TFS, then the Julia bootstrap.
          bash ./tfs-lxd.sh

      - name: Upload artifacts (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfs-logs
          path: |
            artifacts
            /var/snap/lxd/common/lxd/logs
          if-no-files-found: ignore
